### Today, I am going to work with time series and aggregations.

#### We start by introducing the raw DataFrame. In this particular DataFrame, the dates have been uploaded as strings (plain text). The main objective for today is to transform those dates into real date types.

In [1]:
import pandas as pd

raw_data = {
    'Order_ID': ['TX-001', 'TX-002', 'TX-003', 'TX-004', 'TX-005', 'TX-006', 'TX-007', 'TX-008'],
    'Date': ['2024-01-15', '2024-01-22', '2024-02-05', '2024-02-18', '2024-03-10', '2024-03-15', '2024-03-22', '2024-01-19'],
    'Category': ['Hardware', 'Peripherals', 'Hardware', 'Software', 'Software', 'Hardware', 'Peripherals', 'Hardware'],
    'Quantity': [2, 5, 1, 10, 4, 2, 3, 1],
    'Unit_Price': [350.0, 45.0, 800.0, 120.0, 150.0, 400.0, 60.0, 500.0]
}

df_sales = pd.DataFrame(raw_data)

print("Raw Sales Data:")
display(df_sales)

Raw Sales Data:

  Order_ID        Date     Category  Quantity  Unit_Price
0   TX-001  2024-01-15     Hardware         2       350.0
1   TX-002  2024-01-22  Peripherals         5        45.0
2   TX-003  2024-02-05     Hardware         1       800.0
3   TX-004  2024-02-18     Software        10       120.0
4   TX-005  2024-03-10     Software         4       150.0
5   TX-006  2024-03-15     Hardware         2       400.0
6   TX-007  2024-03-22  Peripherals         3        60.0
7   TX-008  2024-01-19     Hardware         1       500.0

#### The first step will be to transform the dates in the 'Date' column to the correct variable type.

In [12]:
print("Before the changes, the Date column variable type is: ")
print("\n")
df_sales.info()
print("\n")

df_sales['Date'] = pd.to_datetime(df_sales['Date'])

print("------------------")
print("\n")
print("After the changes it looks like this: ")
print("\n")
df_sales.info()

Before the changes, the Date column variable type is:


<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       8 non-null      str
 1   Date           8 non-null      datetime64[us]
 2   Category       8 non-null      str
 3   Quantity       8 non-null      int64
 4   Unit_Price     8 non-null      float64
 5   Month          8 non-null      str
 6   Total_revenue  8 non-null      float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 580.0 bytes


------------------


After the changes it looks like this:


<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       8 non-null      str
 1   Date           8 non-null      datetime64[us]
 2   Category       8 non-null      str
 3   Quantity       8 non-null      int64
 4   Unit_Price     8 non-null      float64
 5   Month          8 non-null      str
 6   Total_revenue  8 non-null      float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 580.0 bytes

#### In the second step, I am going to add a new column to the DataFrame with the month of the sale. For this, I will extract the month of the year when the sale was made from the Date column.

In [9]:
df_sales['Month'] = df_sales['Date'].dt.month_name()
print("Now we have the sales discriminated by month: ")
display(df_sales)

Now we have the sales discriminated by month:

  Order_ID       Date     Category  Quantity  Unit_Price     Month
0   TX-001 2024-01-15     Hardware         2       350.0   January
1   TX-002 2024-01-22  Peripherals         5        45.0   January
2   TX-003 2024-02-05     Hardware         1       800.0  February
3   TX-004 2024-02-18     Software        10       120.0  February
4   TX-005 2024-03-10     Software         4       150.0     March
5   TX-006 2024-03-15     Hardware         2       400.0     March
6   TX-007 2024-03-22  Peripherals         3        60.0     March
7   TX-008 2024-01-19     Hardware         1       500.0   January

#### In the third step, I am going to add a new column calculating the total revenue.

In [13]:
Total_revenue = df_sales['Quantity'] * df_sales['Unit_Price']
df_sales['Total_revenue'] = Total_revenue

print("Now we can see the total revenue per sale: ")
display(df_sales)

Now we can see the total revenue per sale:

,Order_ID,Date,Category,Quantity,Unit_Price,Month,Total_revenue
0,TX-001,2024-01-15,Hardware,2,350.0,January,700.0
1,TX-002,2024-01-22,Peripherals,5,45.0,January,225.0
2,TX-003,2024-02-05,Hardware,1,800.0,February,800.0
3,TX-004,2024-02-18,Software,10,120.0,February,1200.0
4,TX-005,2024-03-10,Software,4,150.0,March,600.0
5,TX-006,2024-03-15,Hardware,2,400.0,March,800.0
6,TX-007,2024-03-22,Peripherals,3,60.0,March,180.0
7,TX-008,2024-01-19,Hardware,1,500.0,January,500.0

#### And last but not least, I am going to generate a new DataFrame that stores the aggregated information we extracted from the previous data.

In [14]:
df_summary = df_sales.groupby(['Month', 'Category'])['Total_revenue'].sum().reset_index()

print("And now we have the final result, the summary DataFrame: ")
display(df_summary)

And now we have the final result, the summary DataFrame:

      Month     Category  Total_revenue
0  February     Hardware          800.0
1  February     Software         1200.0
2   January     Hardware         1200.0
3   January  Peripherals          225.0
4     March     Hardware          800.0
5     March  Peripherals          180.0
6     March     Software          600.0