### In today's exercise, I will be working with joins between multiple data sources.

#### In real life, data does not always come from the same place; part of it can be provided by a client database and another from a sales Excel file.
#### To show the procedure I would follow in these cases, I am going to start by creating a simulated merge from two DataFrames.

In [1]:
import pandas as pd

# Day 4: Merging DataFrames (The Pandas JOIN)
# Table 1: Sales transactions
sales_data = {
    'Order_ID': ['TX-101', 'TX-102', 'TX-103', 'TX-104', 'TX-105'],
    'Customer_ID': ['C-01', 'C-02', 'C-01', 'C-03', 'C-02'],
    'Revenue': [450.0, 120.0, 600.0, 300.0, 150.0]
}
df_sales = pd.DataFrame(sales_data)

# Table 2: Customer details
customers_data = {
    'Customer_ID': ['C-01', 'C-02', 'C-03', 'C-04'],
    'Company_Name': ['TechCorp', 'Innova', 'GlobalWorks', 'NextGen'],
    'Country': ['USA', 'Argentina', 'Spain', 'Mexico']
}
df_customers = pd.DataFrame(customers_data)

print("Sales Table:")
display(df_sales)
print("\nCustomers Table:")
display(df_customers)

Sales Table:

  Order_ID Customer_ID  Revenue
0   TX-101        C-01    450.0
1   TX-102        C-02    120.0
2   TX-103        C-01    600.0
3   TX-104        C-03    300.0
4   TX-105        C-02    150.0

Customers Table:

  Customer_ID Company_Name    Country
0        C-01     TechCorp        USA
1        C-02       Innova  Argentina
2        C-03  GlobalWorks      Spain
3        C-04      NextGen     Mexico

#### In this first step, we are going to create a new DataFrame, merging the sales DataFrame and the customers DataFrame.
#### The common point between these two DataFrames is the primary key in the customers table and the foreign key in the sales table, which are the exact same.

In [3]:
df_merged = pd.merge(df_sales, df_customers, on='Customer_ID', how='inner')

print("And the merged dataframe is this: ")
display(df_merged)

And the merged dataframe is this:

  Order_ID Customer_ID  Revenue Company_Name    Country
0   TX-101        C-01    450.0     TechCorp        USA
1   TX-102        C-02    120.0       Innova  Argentina
2   TX-103        C-01    600.0     TechCorp        USA
3   TX-104        C-03    300.0  GlobalWorks      Spain
4   TX-105        C-02    150.0       Innova  Argentina

#### Now that we can see the names of the companies we have made sales to and their countries of origin in the same DataFrame, we can use this data to solve a business question.
#### How much total revenue do we have per country?

In [6]:
df_revenue_by_country = df_merged.groupby('Country')['Revenue'].sum().reset_index()

print("The total revenue per country is: ")
display(df_revenue_by_country)

The total revenue per country is:

     Country  Revenue
0  Argentina    270.0
1      Spain    300.0
2        USA   1050.0