### In today's exercise, we are going to work with ABC Inventory Classification.

#### This is one of the most important analytics to review in the real world. It can be used in logistics, retail, sales, etc.

In [1]:
import pandas as pd
import numpy as np

data = {
    'SKU': ['SKU-01', 'SKU-02', 'SKU-03', 'SKU-04', 'SKU-05', 'SKU-06', 'SKU-07', 'SKU-08'],
    'Description': ['Laptops', 'Mouse', 'Teclados', 'Monitores', 'Cables HDMI', 'Webcams', 'Auriculares', 'Sillas Ergonomicas'],
    'Unit_Cost': [800, 15, 30, 200, 5, 45, 60, 150],
    'Annual_Sold': [120, 500, 300, 80, 1000, 150, 200, 50]
}
df_inventory = pd.DataFrame(data)

print("Datos Crudos de Inventario:")
display(df_inventory)

Datos Crudos de Inventario:

      SKU         Description  Unit_Cost  Annual_Sold
0  SKU-01             Laptops        800          120
1  SKU-02               Mouse         15          500
2  SKU-03            Teclados         30          300
3  SKU-04           Monitores        200           80
4  SKU-05         Cables HDMI          5         1000
5  SKU-06             Webcams         45          150
6  SKU-07         Auriculares         60          200
7  SKU-08  Sillas Ergonomicas        150           50

#### We are going to classify the products in 3 groups:
- Class A: The small group of products that generates 80% of the revenue.
- Class B: Products with intermediate rotation and value.
- Class C: Products that have a low financial impact but occupy most of the physical space.

#### We are going to begin the analysis by creating a new column named Total_Value. This value is the multiplication of the units sold by their unit price.

In [2]:
df_inventory['Total_Value'] = df_inventory['Unit_Cost'] * df_inventory['Annual_Sold']

print("The new column looks like: ")
display(df_inventory)

The new column looks like:

      SKU         Description  Unit_Cost  Annual_Sold  Total_Value
0  SKU-01             Laptops        800          120        96000
1  SKU-02               Mouse         15          500         7500
2  SKU-03            Teclados         30          300         9000
3  SKU-04           Monitores        200           80        16000
4  SKU-05         Cables HDMI          5         1000         5000
5  SKU-06             Webcams         45          150         6750
6  SKU-07         Auriculares         60          200        12000
7  SKU-08  Sillas Ergonomicas        150           50         7500

#### Now we are going to sort the products by their value

In [9]:
df_inventory = df_inventory.sort_values(by='Total_Value', ascending= False).reset_index(drop=True)

print("And the dataframe looks like this: ")
display(df_inventory)

And the dataframe looks like this:

,index,SKU,Description,Unit_Cost,Annual_Sold,Total_Value,Cumulative_Value,Cumulative_Percentage,ABC_Class
0,0,SKU-01,Laptops,800,120,96000,96000,60.093897,A
1,3,SKU-04,Monitores,200,80,16000,112000,70.109546,A
2,6,SKU-07,Auriculares,60,200,12000,124000,77.621283,A
3,2,SKU-03,Teclados,30,300,9000,133000,83.255086,B
4,1,SKU-02,Mouse,15,500,7500,140500,87.949922,B
5,7,SKU-08,Sillas Ergonomicas,150,50,7500,148000,92.644757,B
6,5,SKU-06,Webcams,45,150,6750,154750,96.870110,C
7,4,SKU-05,Cables HDMI,5,1000,5000,159750,100.000000,C

#### Now we are going to calculate what percentage of the whole warehouse each product represents.

In [12]:
df_inventory['Cumulative_Value'] = df_inventory['Total_Value'].cumsum()
total_inventory_value = df_inventory['Total_Value'].sum()

df_inventory['Cumulative_Percentage'] = (df_inventory['Cumulative_Value'] / total_inventory_value) * 100

print("The percentage of each product is: ")
display(df_inventory)

The percentage of each product is:

,index,SKU,Description,Unit_Cost,Annual_Sold,Total_Value,Cumulative_Value,Cumulative_Percentage,ABC_Class
0,0,SKU-01,Laptops,800,120,96000,96000,60.093897,A
1,3,SKU-04,Monitores,200,80,16000,112000,70.109546,A
2,6,SKU-07,Auriculares,60,200,12000,124000,77.621283,A
3,2,SKU-03,Teclados,30,300,9000,133000,83.255086,B
4,1,SKU-02,Mouse,15,500,7500,140500,87.949922,B
5,7,SKU-08,Sillas Ergonomicas,150,50,7500,148000,92.644757,B
6,5,SKU-06,Webcams,45,150,6750,154750,96.870110,C
7,4,SKU-05,Cables HDMI,5,1000,5000,159750,100.000000,C

#### Finally, it is time to classify every product into one of the 3 categories.

In [11]:
conditions = [
    (df_inventory['Cumulative_Percentage'] <= 80),
    (df_inventory['Cumulative_Percentage'] <= 95)
]
choices = ['A', 'B']

df_inventory['ABC_Class'] = np.select(conditions, choices, default='C')

print("ABC Inventory Analysis Results: ")
display(df_inventory[['SKU', 'Description', 'Total_Value', 'Cumulative_Percentage', 'ABC_Class']])

ABC Inventory Analysis Results:

      SKU         Description  Total_Value  Cumulative_Percentage ABC_Class
0  SKU-01             Laptops        96000              60.093897         A
1  SKU-04           Monitores        16000              70.109546         A
2  SKU-07         Auriculares        12000              77.621283         A
3  SKU-03            Teclados         9000              83.255086         B
4  SKU-02               Mouse         7500              87.949922         B
5  SKU-08  Sillas Ergonomicas         7500              92.644757         B
6  SKU-06             Webcams         6750              96.870110         C
7  SKU-05         Cables HDMI         5000             100.000000         C